name: firebase_messaging_example
description: Demonstrates how to use the firebase_messaging plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_core:
    git:
      url: https://github.com/KKimj/flutterfire.git
      ref: upgradejs
      path: packages/firebase_core/firebase_core/
  firebase_messaging: ^14.7.10
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0
  http: ^1.0.0

flutter:
  uses-material-design: true
