name: firebase_auth_web
description: The web implementation of firebase_auth
homepage: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/firebase_auth/firebase_auth_web
version: 5.8.13

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_auth_platform_interface: ^7.0.9
  firebase_core:
    git:
      url: https://github.com/KKimj/flutterfire.git
      ref: upgradejs
      path: packages/firebase_core/firebase_core/
  firebase_core_web:
    git:
      url: https://github.com/KKimj/flutterfire.git
      ref: upgradejs
      path: packages/firebase_core/firebase_core_web/^2.10.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http_parser: ^4.0.0
  js: ^0.7.0
  meta: ^1.8.0
  web: '>=0.3.0 <0.5.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseAuthWeb
        fileName: firebase_auth_web.dart
