name: firebase_performance_example
description: Demonstrates how to use the firebase_performance plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  firebase_core:
    git:
      url: https://github.com/KKimj/flutterfire.git
      ref: upgradejs
      path: packages/firebase_core/firebase_core/
  firebase_performance: ^0.9.3+8
  flutter:
    sdk: flutter
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
