name: firebase_analytics_example
description: Demonstrates how to use the firebase_analytics plugin.

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  firebase_analytics: ^10.8.0
  firebase_core:
    git:
      url: https://github.com/KKimj/flutterfire.git
      ref: upgradejs
      path: packages/firebase_core/firebase_core/
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
