name: cloud_firestore_web
description: The web implementation of cloud_firestore
homepage: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web
repository: https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore/cloud_firestore_web

version: 3.9.0

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  _flutterfire_internals: ^1.3.16
  cloud_firestore_platform_interface: ^6.1.0
  collection: ^1.0.0
  firebase_core:
    git:
      url: https://github.com/KKimj/flutterfire.git
      ref: upgradejs
      path: packages/firebase_core/firebase_core/
  firebase_core_web:
    git:
      url: https://github.com/KKimj/flutterfire.git
      ref: upgradejs
      path: packages/firebase_core/firebase_core_web/^2.10.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.0

dev_dependencies:
  firebase_core_platform_interface: ^5.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FirebaseFirestoreWeb
        fileName: cloud_firestore_web.dart
